Models/Aboba.cs
namespace AbobaApplication.Models
{
    public class Aboba
    {
        public int Id { get; set; }
        
        public string AbobaQuestion { get; set; }

        public string AbobbaAnswer { get; set; }

        public Aboba()
        {
                
        }
    }
}

Models/ErrorViewModel.cs
namespace AbobaApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AbobasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AbobaApplication.Data;
using AbobaApplication.Models;
using Microsoft.AspNetCore.Authorization;

namespace AbobaApplication.Controllers
{
    public class AbobasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AbobasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Abobas
        public async Task<IActionResult> Index()
        {
            return View(await _context.Aboba.ToListAsync());
        }
        
        // GET: Abobas/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }


        // PoST: Abobas/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            return View("Index", await _context.Aboba.Where(filt => filt.AbobaQuestion.Contains(SearchPhrase)).ToListAsync()); 
        }

        // GET: Abobas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aboba = await _context.Aboba
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aboba == null)
            {
                return NotFound();
            }

            return View(aboba);
        }

        [Authorize]

        // GET: Abobas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Abobas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AbobaQuestion,AbobbaAnswer")] Aboba aboba)
        {
            if (ModelState.IsValid)
            {
                _context.Add(aboba);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(aboba);
        }

        [Authorize]
        // GET: Abobas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aboba = await _context.Aboba.FindAsync(id);
            if (aboba == null)
            {
                return NotFound();
            }
            return View(aboba);
        }

        // POST: Abobas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AbobaQuestion,AbobbaAnswer")] Aboba aboba)
        {
            if (id != aboba.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(aboba);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AbobaExists(aboba.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(aboba);
        }

        [Authorize]
        // GET: Abobas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var aboba = await _context.Aboba
                .FirstOrDefaultAsync(m => m.Id == id);
            if (aboba == null)
            {
                return NotFound();
            }

            return View(aboba);
        }


        // POST: Abobas/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var aboba = await _context.Aboba.FindAsync(id);
            if (aboba != null)
            {
                _context.Aboba.Remove(aboba);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AbobaExists(int id)
        {
            return _context.Aboba.Any(e => e.Id == id);
        }
    }
}

Controllers/HomeController.cs
using AbobaApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AbobaApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Abobas/Create.cshtml
@model AbobaApplication.Models.Aboba

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Aboba</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AbobaQuestion" class="control-label"></label>
                <input asp-for="AbobaQuestion" class="form-control" />
                <span asp-validation-for="AbobaQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AbobbaAnswer" class="control-label"></label>
                <input asp-for="AbobbaAnswer" class="form-control" />
                <span asp-validation-for="AbobbaAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Abobas/Delete.cshtml
@model AbobaApplication.Models.Aboba

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aboba</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbobaQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbobaQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbobbaAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbobbaAnswer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Abobas/Details.cshtml
@model AbobaApplication.Models.Aboba

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Aboba</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbobaQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbobaQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbobbaAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbobbaAnswer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Abobas/Edit.cshtml
@model AbobaApplication.Models.Aboba

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Aboba</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="AbobaQuestion" class="control-label"></label>
                <input asp-for="AbobaQuestion" class="form-control" />
                <span asp-validation-for="AbobaQuestion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AbobbaAnswer" class="control-label"></label>
                <input asp-for="AbobbaAnswer" class="form-control" />
                <span asp-validation-for="AbobbaAnswer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Abobas/Index.cshtml
@model IEnumerable<AbobaApplication.Models.Aboba>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AbobaQuestion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AbobaQuestion)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Abobas/ShowSearchForm.cshtml
@{
    ViewData["Title"] = "ShowSearchForm";
}


<h4>Search for an Aboba</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Abobas/ShowSearchResults.cshtml
@model AbobaApplication.Models.Aboba

<div>
    <h4>Aboba</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbobaQuestion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbobaQuestion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AbobbaAnswer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AbobbaAnswer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This is application about Aboba and his friend Lumbego.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AbobaApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AbobaApplication.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AbobaApplication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Abobas" asp-action="Index">Abobas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Abobas" asp-action="ShowSearchForm">Finding mama</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AbobaApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap.min.js"></script>
    <script src="~/lib/htmx.min.js"></script>
    <script src="~/js/_hyperscript.min.js"></script>
    @await RenderSectionAsync("end", required: false)
</body>
</html>